package project2;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class screen extends JPanel {
    private JTextField jcomp1;
    private JTextField jcomp2;
    private JTextField jcomp3;
    private JTextField jcomp4;
    private JTextArea jcomp5;
    private JTextArea jcomp6;

    public screen() {
        //construct components
        jcomp1 = new JTextField (5);
        jcomp2 = new JTextField (5);
        jcomp3 = new JTextField (5);
        jcomp4 = new JTextField (5);
        jcomp5 = new JTextArea (5, 5);
        jcomp6 = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 558));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (175, 65, 225, 80);
        jcomp1.setBorder(null);
        jcomp1.setEditable(false);
        jcomp1.setText("DEPOSIT");
        jcomp1.setBackground(new Color(0xFFFFFF));
        jcomp2.setBounds (175, 140, 225, 80);
        jcomp2.setBorder(null);
        jcomp3.setBounds (175, 215, 225, 80);
        jcomp3.setBorder(null);
        jcomp4.setBounds (395, 65, 225, 80);
        jcomp4.setBorder(null);
        jcomp5.setBounds (395, 140, 225, 80);
        jcomp5.setBorder(null);
        jcomp6.setBounds (395, 215, 225, 80);
        jcomp6.setBorder(null);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new screen());
        frame.pack();
        frame.setVisible (true);
    }
}

